"""Self-contained mirror of Perturb validator inference, scoring, and challenge I/O."""

from perturb_mirror.constants import (
    IMAGENET100_REPO_ID,
    IMAGENET100_SPLIT,
    LINF_COMPONENT_WEIGHT,
    MAX_LINF_DELTA,
    MIN_LINF_DELTA,
    MIN_PSNR_DB,
    MIN_SSIM,
    MODEL_NAME,
    PERTURBATION_WEIGHT,
    RMSE_COMPONENT_WEIGHT,
    SPEED_WEIGHT,
    SUBNET_NAMESPACE,
    TIMEOUT_SECONDS,
)
from perturb_mirror.image_io import decode_image_b64, decode_image_b64_to_numpy, encode_image_b64
from perturb_mirror.imagenet100_bootstrap import imagenet100_dataset_version, load_imagenet100
from perturb_mirror.model import (
    LABELS,
    LABEL_TO_INDEX,
    PREPROCESS,
    WEIGHTS,
    _preprocess_for_efficientnet_v2_l,
    load_efficientnet_v2_l,
    logits_for_images,
    normalize_prediction_label,
    predict_index,
    predict_label,
    resolve_target_index,
)
from perturb_mirror.scoring import (
    ChallengeSpec,
    EvaluationResult,
    ScoringConfig,
    compute_psnr_db,
    compute_ssim,
    verify_and_score,
)
from perturb_mirror.validator import (
    baseline_miner_forward,
    build_challenge_spec,
    derive_true_label,
    sample_epsilon,
    score_miner_response,
)

__all__ = [
    "ChallengeSpec",
    "EvaluationResult",
    "IMAGENET100_REPO_ID",
    "IMAGENET100_SPLIT",
    "LABELS",
    "LABEL_TO_INDEX",
    "LINF_COMPONENT_WEIGHT",
    "MAX_LINF_DELTA",
    "MIN_LINF_DELTA",
    "MIN_PSNR_DB",
    "MIN_SSIM",
    "MODEL_NAME",
    "PERTURBATION_WEIGHT",
    "PREPROCESS",
    "RMSE_COMPONENT_WEIGHT",
    "ScoringConfig",
    "SPEED_WEIGHT",
    "SUBNET_NAMESPACE",
    "TIMEOUT_SECONDS",
    "WEIGHTS",
    "_preprocess_for_efficientnet_v2_l",
    "baseline_miner_forward",
    "build_challenge_spec",
    "compute_psnr_db",
    "compute_ssim",
    "decode_image_b64",
    "decode_image_b64_to_numpy",
    "derive_true_label",
    "encode_image_b64",
    "imagenet100_dataset_version",
    "load_efficientnet_v2_l",
    "load_imagenet100",
    "logits_for_images",
    "normalize_prediction_label",
    "predict_index",
    "predict_label",
    "resolve_target_index",
    "sample_epsilon",
    "score_miner_response",
    "verify_and_score",
]
